project:
  type: website
  output-dir: _site

website:
  title: "Nandani Arora"
  site-url: https://nandaniarora.github.io/Nandani/
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Education
        href: Education.qmd
      - text: Professional Experience
        href: Professional Experience.qmd
      - text: Skills & Certifications
        href: Skills & Certifications.qmd
      - text: Projects
        href: Projects.qmd
      - text: Contact
        href: Contact.qmd
      - text: Leadership & Community Service
        href: Leadership.qmd


  format:
  html:
    theme: cosmo
    toc: true
    navbar:
      background: "#ffffff"
      fixed: true
  



